services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aplicacao
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    environment:
      CI_ENV: development
      DB_HOST: db_sgp
      DB_DATABASE: sgp
      DB_USERNAME: root
      DB_PASSWORD: root
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: banco
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sgp
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: